name: Deploy Docker App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on Ubuntu Server
        run: |
          /home/sinhvien/deploy-thitracnghiem.sh